### ISSUE TITLE
No module named 'custom_components.basestation.sensor'

### ISSUE THREAD

**Issue by kevinfoerster** [jariz/homeassistant-basestation#1]
I think I setup the custom component correctly but setting up the sensors will result in

```
Platform error sensor.basestation - No module named 'custom_components.basestation.sensor' 
Platform error sensor.basestation - No module named 'custom_components.basestation.sensor' 
Platform error sensor.basestation - No module named 'custom_components.basestation.sensor'
````

I checked the custom_components folder and the component was installed correctly as far as I can tell.

the following code was used to setup the component
```
sensor:
  - platform: basestation
    mac: "xx:xx:xx:xx:xx:xx"
    name: "LHB 1"
  - platform: basestation
    mac: "xx:xx:xx:xx:xx:xx"
    name: "LHB 2"
  - platform: basestation
    mac: "xx:xx:xx:xx:xx:xx"
    name: "LHB 3"
```

running the latest version (2021.4.0) of home assistant if this is important. 

home assistant runs inside a docker container and I tried to run `hcitool lescan` from within the container, to see the bluetooth devices, which showed up properly.

I also configured the switches in a similar way and they do not show up either.
